version: "3.2"

services:
  postgresql:
    container_name: workflow-generator-backend-postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: workflow
      POSTGRES_USER: workflow
      POSTGRES_PASSWORD: workflow
    ports:
      - "5432:5432"
    restart: always
