openapi: "3.0.0"
info:
  version: 0.0.1
  title: Workflow Generator
tags:
- name: workflows
  description: Create and manage workflows
paths:
  /auth/login:
    post:
      tags:
      - auth
      summary: Login using stud.ip credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: Successful login
          headers:
            Authorization:
              description: Bearer token to use for future requests
              schema:
                type: string
        401:
          description: Invalid credentials

  /forms:
    post:
      tags:
      - forms
      summary: Create a new form
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFormRequest"
      responses:
        201:
          description: Form created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
        401:
          description: Invalid credentials

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token received from the /auth/login endpoint
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password
    CreateFormRequest:
      type: object
      properties:
        uniqueFormElements:
          type: array
          items:
            $ref: "#/components/schemas/FormElement"
        perms:
          $ref: "#/components/schemas/Scope"
    Form:
      type: object
      properties:
        id:
          type: string
          format: uuid
        uniqueFormElements:
          type: array
          items:
            $ref: "#/components/schemas/FormElement"
        perms:
          $ref: "#/components/schemas/Scope"
    FormElement:
      oneOf:
      - type: object
        properties:
          type:
            type: string
            enum:
            - TextField
          id:
            type: string
          label:
            type: string
      - type: object
        properties:
          type:
            type: string
            enum:
            - NumberField
          id:
            type: string
          label:
            type: string
      - type: object
        properties:
          type:
            type: string
            enum:
            - DateFicker
          id:
            type: string
          label:
            type: string
    Scope:
      oneOf:
      - type: object
        properties:
          type:
            type: string
            enum:
            - Admin
        required:
        - type
      - type: object
        properties:
          type:
            type: string
            enum:
            - ForGroups
          groups:
            type: array
            items:
              type: string
        required:
        - type
        - groups
      - type: object
        properties:
          type:
            type: string
            enum:
            - ForUsers
          users:
            type: array
            items:
              type: string
        required:
        - type
        - users
