addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.9.27")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"              % "0.15.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"       % "1.8.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.4.2")
