name: Autoupdate PRs
on:
  push: {}

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GH_ADMIN_TOKEN }}'
          PR_FILTER: labelled
          PR_LABELS: autoupdate
          MERGE_CONFLICT_ACTION: ignore
