name: Automerge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          merge-method: squash
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          pull-request-author-associations: "MEMBER,OWNER"
