name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Configure cachix
      uses: cachix/cachix-action@v8
      with:
        name: mschuwalow
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Lint
      run: |
        nix develop --command sh -c "sbt fixCheck"

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Configure cachix
      uses: cachix/cachix-action@v8
      with:
        name: mschuwalow
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Start docker-compose
      run: |
        docker-compose up -d
    - name: Run tests
      run: |
        nix develop --command sh -c "sbt test"
    - name: Stop docker-compose
      run: |
        docker-compose down

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
      - name: Aggregate job outcomes
        run: echo "build succeeded"
