name: "Publish to Docker Hub"
on:
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Configure cachix
      uses: cachix/cachix-action@v8
      with:
        name: mschuwalow
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: |
        nix build .#docker
    - name: Push image to Docker Hub
      run: |
        VERSION="$(date '+%Y.%m.%d')-${GITHUB_SHA::7}"
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/workflow-generator-backend:$VERSION"
        docker load < result
        docker tag workflow-generator-backend $IMAGE_NAME
        docker push $IMAGE_NAME

